### ISSUE TITLE
Documentation should point to native mode

### ISSUE THREAD

**Issue by judy-akers** [docksal/drupal7#7]
The documentation link should point to the native mode installation for Docker. The difference between the two is very confusing for most users, so the difference between the two methods of setting up the environment should be explained in a paragraph or so. After that, provide a link to the native mode setup:

http://docksal.readthedocs.io/en/master/getting-started/env-setup-native/

Indeed, we have found Docksal for Drupal pretty much impossible to set up on Windows using the old method due to conflicts between Hyper-V and VirtualBox.

**Comment by achekulaev** [comment]
Good point @judy-akers. This ticket is related to Docksal overall and should be in docksal/docksal queue though. I have moved it there: https://github.com/docksal/docksal/issues/453 
You can subscribe to it's updates if needed.

I'm closing this one in favor of that one.
